<%@ Page Language="C#" MasterPageFile ="~/MasterPage.master" AutoEventWireup="true" CodeFile="admin_feedback.aspx.cs" Inherits="admin_feedback" %>

<asp:Content ID="content" ContentPlaceHolderID ="slider" runat ="server">
<center>
    <asp:GridView ID="GridView1" Height ="500px" Width ="1000px" runat="server" 
        BorderColor ="Black" BorderWidth ="20px" 
        AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
        DataSourceID="SqlDataSource1" DataKeyNames="id">
        <Columns>
            <asp:BoundField DataField="name" HeaderText="name" SortExpression="name" />
            <asp:BoundField DataField="feedback" HeaderText="feedback" 
                SortExpression="feedback" />
            <asp:BoundField DataField="id" HeaderText="id" InsertVisible="False" 
                ReadOnly="True" SortExpression="id" />
        </Columns>
    </asp:GridView>
    </center>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:job_portalConnectionString %>" 
        SelectCommand="SELECT [name], [feedback], [id] FROM [feedback]" DeleteCommand="delete from feedback where id=@id
"></asp:SqlDataSource>
        <center><asp:LinkButton ID="logout" runat ="server" Text="LogOut" PostBackUrl ="~/Admin_Login.aspx"></asp:LinkButton></center>
</asp:Content>